# Generated by Django 3.2.7 on 2021-10-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sum',
            name='total_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
