# Generated by Django 3.2.7 on 2021-10-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sum', '0002_sum_total_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sum',
            new_name='SumNumber',
        ),
    ]
