# Generated by Django 3.2.7 on 2021-10-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum', '0003_rename_sum_sumnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumnumber',
            name='total_number',
            field=models.IntegerField(default=0),
        ),
    ]
